using CortexTerminal.Gateway.Contracts.Auth;

namespace CortexTerminal.Gateway.Extensions;

internal static class WorkerInstallScriptBuilder
{
    private const string DefaultPackageBaseUrl = "https://github.com/rwecho/CortexTerminal/releases/latest/download";

    public static WorkerInstallCommandSet BuildCommandSet(string gatewayBaseUrl, string token)
    {
        var unixUrl = BuildUnixInstallUrl(gatewayBaseUrl, token);
        var windowsUrl = BuildWindowsInstallUrl(gatewayBaseUrl, token);

        return new WorkerInstallCommandSet(
            unixUrl,
            BuildUnixCommand(unixUrl),
            windowsUrl,
            BuildWindowsCommand(windowsUrl));
    }

    public static string BuildUnixScript(string gatewayBaseUrl, string token)
    {
        return string.Join("\n",
        [
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            string.Empty,
            $"gateway_base_url={ShellEscape(gatewayBaseUrl)}",
            $"install_token={ShellEscape(token)}",
            "install_dir=\"${CORTEX_WORKER_INSTALL_DIR:-$HOME/.cortex-terminal/worker}\"",
            "package_base_url=\"${CORTEX_WORKER_PACKAGE_BASE_URL:-" + DefaultPackageBaseUrl + "}\"",
            "force_install=\"${CORTEX_WORKER_INSTALL_FORCE:-true}\"",
            string.Empty,
            "log() {",
            "  printf '[cortex-worker-install] %s\\n' \"$1\"",
            "}",
            string.Empty,
            "fail() {",
            "  printf '[cortex-worker-install] ERROR: %s\\n' \"$1\" >&2",
            "  exit 1",
            "}",
            string.Empty,
            "require_command() {",
            "  command -v \"$1\" >/dev/null 2>&1 || fail \"missing required command: $1\"",
            "}",
            string.Empty,
            "random_suffix() {",
            "  hexdump -n 4 -e '4/1 \"%02x\"' /dev/urandom | cut -c 1-6",
            "}",
            string.Empty,
            "normalize_hostname() {",
            "  local host_name",
            "  host_name=\"$(hostname -s 2>/dev/null || hostname 2>/dev/null || echo worker)\"",
            "  printf '%s' \"$host_name\" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-*//; s/-*$//'",
            "}",
            string.Empty,
            "sanitize_service_identifier() {",
            "  local value=\"${1:-worker}\"",
            "  printf '%s' \"$value\" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9._-' '-' | sed 's/^-*//; s/-*$//'",
            "}",
            string.Empty,
            "xml_escape() {",
            "  local value=\"${1:-}\"",
            "  value=${value//&/&amp;}",
            "  value=${value//</&lt;}",
            "  value=${value//>/&gt;}",
            "  printf '%s' \"$value\"",
            "}",
            string.Empty,
            "read_file_value() {",
            "  local file_path=\"$1\"",
            "  [[ -f \"$file_path\" ]] || return 0",
            "  tr -d '\\r\\n' < \"$file_path\"",
            "}",
            string.Empty,
            "normalize_package_version() {",
            "  local version_value=\"${1:-}\"",
            "  version_value=\"${version_value#v}\"",
            "  printf '%s' \"$version_value\"",
            "}",
            string.Empty,
            "is_comparable_package_version() {",
            "  local version_value",
            "  version_value=\"$(normalize_package_version \"$1\")\"",
            "  [[ \"$version_value\" =~ ^[0-9]+(\\.[0-9]+){1,3}$ ]]",
            "}",
            string.Empty,
            "compare_package_versions() {",
            "  local incoming_version installed_version max_version",
            "  incoming_version=\"$(normalize_package_version \"$1\")\"",
            "  installed_version=\"$(normalize_package_version \"$2\")\"",
            string.Empty,
            "  if [[ -z \"$incoming_version\" || -z \"$installed_version\" ]]; then",
            "    printf 'unknown'",
            "    return 0",
            "  fi",
            string.Empty,
            "  if [[ \"$incoming_version\" == \"$installed_version\" ]]; then",
            "    printf 'same'",
            "    return 0",
            "  fi",
            string.Empty,
            "  if is_comparable_package_version \"$incoming_version\" && is_comparable_package_version \"$installed_version\"; then",
            "    max_version=\"$(printf '%s\\n%s\\n' \"$incoming_version\" \"$installed_version\" | sort -V | tail -n 1)\"",
            "    if [[ \"$max_version\" == \"$incoming_version\" ]]; then",
            "      printf 'newer'",
            "    else",
            "      printf 'older'",
            "    fi",
            string.Empty,
            "    return 0",
            "  fi",
            string.Empty,
            "  printf 'unknown'",
            "}",
            string.Empty,
            "read_env_value() {",
            "  local key=\"$1\" file_path=\"$2\"",
            "  [[ -f \"$file_path\" ]] || return 0",
            "  awk -F= -v key=\"$key\" '$1 == key { print substr($0, index($0, \"=\") + 1) }' \"$file_path\" | tail -n 1",
            "}",
            string.Empty,
            "upsert_env_value() {",
            "  local key=\"$1\" value=\"$2\" file_path=\"$3\" temp_file",
            "  mkdir -p \"$(dirname \"$file_path\")\"",
            "  [[ -f \"$file_path\" ]] || touch \"$file_path\"",
            "  temp_file=\"$(mktemp)\"",
            "  awk -v key=\"$key\" -v value=\"$value\" 'BEGIN { updated = 0 } $0 ~ (\"^\" key \"=\") { if (!updated) { print key \"=\" value; updated = 1 } next } { print } END { if (!updated) print key \"=\" value }' \"$file_path\" > \"$temp_file\"",
            "  mv \"$temp_file\" \"$file_path\"",
            "}",
            string.Empty,
            "ensure_env_value() {",
            "  local key=\"$1\" value=\"$2\" file_path=\"$3\" existing_value",
            "  existing_value=\"$(read_env_value \"$key\" \"$file_path\")\"",
            "  if [[ -z \"$existing_value\" ]]; then",
            "    upsert_env_value \"$key\" \"$value\" \"$file_path\"",
            "  fi",
            "}",
            string.Empty,
            "install_or_update_systemd_user_service() {",
            "  local service_name=\"$1\" display_name=\"$2\" launcher_path=\"$3\" working_dir=\"$4\" env_file=\"$5\" logs_dir=\"$6\"",
            "  local systemd_user_dir service_file",
            "  require_command systemctl",
            "  systemd_user_dir=\"${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user\"",
            "  service_file=\"$systemd_user_dir/$service_name.service\"",
            "  mkdir -p \"$systemd_user_dir\" \"$logs_dir\"",
            string.Empty,
            "  cat >\"$service_file\" <<EOF",
            "[Unit]",
            "Description=Cortex Terminal worker service for $display_name",
            "After=default.target",
            string.Empty,
            "[Service]",
            "Type=simple",
            "WorkingDirectory=$working_dir",
            "Environment=CORTEX_WORKER_ENV_FILE=$env_file",
            "ExecStart=$launcher_path",
            "Restart=always",
            "RestartSec=5",
            "StandardOutput=append:$logs_dir/worker-service.stdout.log",
            "StandardError=append:$logs_dir/worker-service.stderr.log",
            string.Empty,
            "[Install]",
            "WantedBy=default.target",
            "EOF",
            string.Empty,
            "  log \"reloading systemd user daemon\"",
            "  systemctl --user daemon-reload",
            "  systemctl --user enable \"$service_name.service\" >/dev/null",
            "  systemctl --user restart \"$service_name.service\"",
            "}",
            string.Empty,
            "install_or_update_launchd_agent() {",
            "  local service_label=\"$1\" display_name=\"$2\" launcher_path=\"$3\" working_dir=\"$4\" env_file=\"$5\" logs_dir=\"$6\"",
            "  local launch_agents_dir plist_path user_id bootstrap_output primary_domain fallback_domain active_domain label_target",
            "  require_command launchctl",
            "  launch_agents_dir=\"$HOME/Library/LaunchAgents\"",
            "  plist_path=\"$launch_agents_dir/$service_label.plist\"",
            "  user_id=\"$(id -u)\"",
            "  primary_domain=\"gui/$user_id\"",
            "  fallback_domain=\"user/$user_id\"",
            "  mkdir -p \"$launch_agents_dir\" \"$logs_dir\"",
            string.Empty,
            "  cat >\"$plist_path\" <<EOF",
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
            "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">",
            "<plist version=\"1.0\">",
            "<dict>",
            "  <key>Label</key>",
            "  <string>$service_label</string>",
            "  <key>ProgramArguments</key>",
            "  <array>",
            "    <string>$(xml_escape \"$launcher_path\")</string>",
            "  </array>",
            "  <key>EnvironmentVariables</key>",
            "  <dict>",
            "    <key>CORTEX_WORKER_ENV_FILE</key>",
            "    <string>$(xml_escape \"$env_file\")</string>",
            "  </dict>",
            "  <key>WorkingDirectory</key>",
            "  <string>$(xml_escape \"$working_dir\")</string>",
            "  <key>StandardOutPath</key>",
            "  <string>$(xml_escape \"$logs_dir/worker-service.stdout.log\")</string>",
            "  <key>StandardErrorPath</key>",
            "  <string>$(xml_escape \"$logs_dir/worker-service.stderr.log\")</string>",
            "  <key>RunAtLoad</key>",
            "  <true/>",
            "  <key>KeepAlive</key>",
            "  <true/>",
            "</dict>",
            "</plist>",
            "EOF",
            string.Empty,
            "  for active_domain in \"$primary_domain\" \"$fallback_domain\"; do",
            "    label_target=\"$active_domain/$service_label\"",
            "    launchctl bootout \"$label_target\" >/dev/null 2>&1 || true",
            "    if bootstrap_output=\"$(launchctl bootstrap \"$active_domain\" \"$plist_path\" 2>&1)\"; then",
            "      launchctl enable \"$label_target\" >/dev/null 2>&1 || true",
            "      if bootstrap_output=\"$(launchctl kickstart -k \"$label_target\" 2>&1)\"; then",
            "        return 0",
            "      fi",
            "    fi",
            "  done",
            "  log \"warning: launchd agent file was created, but automatic loading failed in both $primary_domain and $fallback_domain\"",
            "  if [[ -n \"${bootstrap_output:-}\" ]]; then",
            "    log \"launchctl output: $bootstrap_output\"",
            "  fi",
            "  log \"you can try again later with: launchctl bootstrap $primary_domain $plist_path\"",
            "  log \"or start the worker manually with: $launcher_path\"",
            "  return 1",
            "}",
            string.Empty,
            "resolve_asset() {",
            "  local os_name arch_name",
            "  os_name=\"$(uname -s)\"",
            "  arch_name=\"$(uname -m)\"",
            string.Empty,
            "  case \"$os_name/$arch_name\" in",
            "    Darwin/arm64)",
            "      printf 'cortex-terminal-worker-osx-arm64.tar.gz osx-arm64'",
            "      ;;",
            "    Linux/x86_64)",
            "      printf 'cortex-terminal-worker-linux-x64.tar.gz linux-x64'",
            "      ;;",
            "    *)",
            "      fail \"unsupported platform: $os_name/$arch_name\"",
            "      ;;",
            "  esac",
            "}",
            string.Empty,
            "require_command curl",
            "require_command tar",
            "require_command hexdump",
            string.Empty,
            "read -r worker_asset_name worker_package_dir <<<\"$(resolve_asset)\"",
            "package_url=\"$package_base_url/$worker_asset_name\"",
            "temp_dir=\"$(mktemp -d)\"",
            "archive_path=\"$temp_dir/$worker_asset_name\"",
            "trap 'rm -rf \"$temp_dir\"' EXIT",
            string.Empty,
            "log \"downloading worker package from $package_url\"",
            "curl -fsSL \"$package_url\" -o \"$archive_path\"",
            "log \"extracting worker package\"",
            "tar -xzf \"$archive_path\" -C \"$temp_dir\"",
            string.Empty,
            "package_root=\"$temp_dir/$worker_package_dir\"",
            "install_script=\"$package_root/scripts/install-worker.sh\"",
            "package_version=\"$(read_file_value \"$package_root/package-version.txt\")\"",
            "installed_version=\"$(read_file_value \"$install_dir/package-version.txt\")\"",
            "version_comparison=\"$(compare_package_versions \"$package_version\" \"$installed_version\")\"",
            "install_payload=true",
            string.Empty,
            "case \"$version_comparison\" in",
            "  same)",
            "    log \"worker version $package_version is already installed at $install_dir; refreshing managed service configuration\"",
            "    install_payload=false",
            "    ;;",
            "  older)",
            "    fail \"refusing to downgrade worker from $installed_version to $package_version\"",
            "    ;;",
            "  newer)",
            "    log \"upgrading worker from $installed_version to $package_version\"",
            "    ;;",
            "esac",
            string.Empty,
            "bootstrap_payload=\"{\\\"token\\\":\\\"${install_token}\\\"}\"",
            "log \"requesting worker registration key\"",
            "registration_key_response_path=\"$temp_dir/worker-registration-key.response\"",
            "registration_key_http_status=\"$(curl -sS -o \"$registration_key_response_path\" -w '%{http_code}' \"$gateway_base_url/api/worker/install/registration-key\" \\",
            "  -H 'Content-Type: application/json' \\",
            "  -X POST \\",
            "  --data \"$bootstrap_payload\")\"",
            "if [[ \"$registration_key_http_status\" -lt 200 || \"$registration_key_http_status\" -ge 300 ]]; then",
            "  registration_key_error=\"$(tr -d '\\r' < \"$registration_key_response_path\")\"",
            "  fail \"failed to request worker registration key (HTTP $registration_key_http_status): ${registration_key_error:-no response body}\"",
            "fi",
            "worker_registration_key=\"$(tr -d '\\r\\n' < \"$registration_key_response_path\")\"",
            string.Empty,
            "if [[ -z \"$worker_registration_key\" ]]; then",
            "  fail 'gateway returned an empty registration key'",
            "fi",
            string.Empty,
            "if [[ \"$install_payload\" == \"true\" ]]; then",
            "  [[ -x \"$install_script\" ]] || chmod +x \"$install_script\"",
            string.Empty,
            "  if [[ \"$force_install\" == \"true\" ]]; then",
            "    \"$install_script\" --install-dir \"$install_dir\" --force",
            "  else",
            "    \"$install_script\" --install-dir \"$install_dir\"",
            "  fi",
            "fi",
            string.Empty,
            "config_dir=\"$install_dir/config\"",
            "env_file=\"$config_dir/worker.env\"",
            "launcher_path=\"$install_dir/run-worker.sh\"",
            "uninstall_path=\"$install_dir/uninstall-worker.sh\"",
            "logs_dir=\"$install_dir/logs\"",
            "mkdir -p \"$config_dir\"",
            "existing_worker_id=\"$(read_env_value WORKER_ID \"$env_file\")\"",
            "worker_name=\"${existing_worker_id:-$(normalize_hostname)-$(random_suffix)}\"",
            "worker_display_name=\"$worker_name\"",
            string.Empty,
            "upsert_env_value GATEWAY_BASE_URL \"$gateway_base_url\" \"$env_file\"",
            "upsert_env_value WORKER_ID \"$worker_name\" \"$env_file\"",
            "ensure_env_value WORKER_USER_KEY \"$worker_registration_key\" \"$env_file\"",
            "ensure_env_value WORKER_LOG_LEVEL Information \"$env_file\"",
            string.Empty,
            "mkdir -p \"$logs_dir\"",
            "case \"$(uname -s)\" in",
            "  Linux)",
            "    unix_service_name=\"cortex-terminal-worker-$(sanitize_service_identifier \"$worker_name\")\"",
            "    log \"installing systemd user service $unix_service_name\"",
            "    install_or_update_systemd_user_service \"$unix_service_name\" \"$worker_display_name\" \"$launcher_path\" \"$install_dir\" \"$env_file\" \"$logs_dir\"",
            "    log \"systemd user service installed and started: $unix_service_name\"",
            "    ;;",
            "  Darwin)",
            "    unix_service_name=\"top.rwecho.cortex-terminal.worker.$(sanitize_service_identifier \"$worker_name\")\"",
            "    log \"installing launchd agent $unix_service_name\"",
            "    if install_or_update_launchd_agent \"$unix_service_name\" \"$worker_display_name\" \"$launcher_path\" \"$install_dir\" \"$env_file\" \"$logs_dir\"; then",
            "      log \"launchd agent installed and started: $unix_service_name\"",
            "    else",
            "      log \"launchd agent plist was created at $HOME/Library/LaunchAgents/$unix_service_name.plist, but automatic startup could not be enabled from this shell\"",
            "    fi",
            "    ;;",
            "  *)",
            "    fail \"unsupported Unix service platform: $(uname -s)\"",
            "    ;;",
            "esac",
            string.Empty,
            "log \"worker installed to $install_dir\"",
            "log \"managed worker service is active for $worker_display_name\"",
            "log \"uninstall with: $uninstall_path\""
        ]);
    }

    public static string BuildWindowsScript(string gatewayBaseUrl, string token)
    {
        return string.Join("\r\n",
        [
            "param(",
            "    [string]$InstallDir = $(if ($env:CORTEX_WORKER_INSTALL_DIR) { $env:CORTEX_WORKER_INSTALL_DIR } else { Join-Path $HOME '.cortex-terminal/worker' })",
            ")",
            string.Empty,
            "$ErrorActionPreference = 'Stop'",
            $"$gatewayBaseUrl = {PowerShellEscape(gatewayBaseUrl)}",
            $"$installToken = {PowerShellEscape(token)}",
            "$packageBaseUrl = if ($env:CORTEX_WORKER_PACKAGE_BASE_URL) { $env:CORTEX_WORKER_PACKAGE_BASE_URL } else { '" + DefaultPackageBaseUrl + "' }",
            string.Empty,
            "function Resolve-ForceInstall {",
            "    if ([string]::IsNullOrWhiteSpace($env:CORTEX_WORKER_INSTALL_FORCE)) {",
            "        return $true",
            "    }",
            string.Empty,
            "    switch ($env:CORTEX_WORKER_INSTALL_FORCE.Trim().ToLowerInvariant()) {",
            "        '0' { return $false }",
            "        'false' { return $false }",
            "        'no' { return $false }",
            "        default { return $true }",
            "    }",
            "}",
            string.Empty,
            "$forceInstall = Resolve-ForceInstall",
            string.Empty,
            "function Log([string]$Message) {",
            "    Write-Host \"[cortex-worker-install] $Message\"",
            "}",
            string.Empty,
            "function Fail([string]$Message) {",
            "    throw \"[cortex-worker-install] ERROR: $Message\"",
            "}",
            string.Empty,
            "function Normalize-HostName([string]$Value) {",
            "    $normalized = $Value.ToLowerInvariant() -replace '[^a-z0-9]+', '-'",
            "    $normalized = $normalized.Trim('-')",
            "    if ([string]::IsNullOrWhiteSpace($normalized)) {",
            "        return 'worker'",
            "    }",
            string.Empty,
            "    return $normalized",
            "}",
            string.Empty,
            "function Get-WorkerHomePath {",
            "    $homePath = [Environment]::GetFolderPath([Environment+SpecialFolder]::UserProfile)",
            "    if ([string]::IsNullOrWhiteSpace($homePath)) {",
            "        return $HOME",
            "    }",
            string.Empty,
            "    return $homePath",
            "}",
            string.Empty,
            "function Read-VersionFile([string]$Path) {",
            "    if (-not (Test-Path $Path)) {",
            "        return $null",
            "    }",
            string.Empty,
            "    return (Get-Content -Path $Path -Raw).Trim()",
            "}",
            string.Empty,
            "function Normalize-PackageVersion([string]$Value) {",
            "    if ([string]::IsNullOrWhiteSpace($Value)) {",
            "        return $null",
            "    }",
            string.Empty,
            "    return $Value.Trim().TrimStart('v')",
            "}",
            string.Empty,
            "function Compare-PackageVersion([string]$IncomingVersion, [string]$InstalledVersion) {",
            "    $incomingNormalized = Normalize-PackageVersion $IncomingVersion",
            "    $installedNormalized = Normalize-PackageVersion $InstalledVersion",
            string.Empty,
            "    if ([string]::IsNullOrWhiteSpace($incomingNormalized) -or [string]::IsNullOrWhiteSpace($installedNormalized)) {",
            "        return 'Unknown'",
            "    }",
            string.Empty,
            "    if ($incomingNormalized -eq $installedNormalized) {",
            "        return 'Same'",
            "    }",
            string.Empty,
            "    $incomingParsed = $null",
            "    $installedParsed = $null",
            "    if ([Version]::TryParse($incomingNormalized, [ref]$incomingParsed) -and [Version]::TryParse($installedNormalized, [ref]$installedParsed)) {",
            "        $comparison = $incomingParsed.CompareTo($installedParsed)",
            "        if ($comparison -gt 0) { return 'Newer' }",
            "        if ($comparison -lt 0) { return 'Older' }",
            "        return 'Same'",
            "    }",
            string.Empty,
            "    return 'Unknown'",
            "}",
            string.Empty,
            "function Read-EnvValue([string]$Path, [string]$Key) {",
            "    if (-not (Test-Path $Path)) {",
            "        return $null",
            "    }",
            string.Empty,
            "    foreach ($line in Get-Content -Path $Path) {",
            "        if ($line -match '^[\\s#]' -or [string]::IsNullOrWhiteSpace($line)) {",
            "            continue",
            "        }",
            string.Empty,
            "        $parts = $line -split '=', 2",
            "        if ($parts.Length -eq 2 -and $parts[0] -eq $Key) {",
            "            return $parts[1]",
            "        }",
            "    }",
            string.Empty,
            "    return $null",
            "}",
            string.Empty,
            "function Set-OrAppendEnvValue([string]$Path, [string]$Key, [string]$Value) {",
            "    $lines = New-Object System.Collections.Generic.List[string]",
            "    $updated = $false",
            "    if (Test-Path $Path) {",
            "        foreach ($line in Get-Content -Path $Path) {",
            "            if ($line -match '^[\\s#]' -or [string]::IsNullOrWhiteSpace($line)) {",
            "                $lines.Add($line)",
            "                continue",
            "            }",
            string.Empty,
            "            $parts = $line -split '=', 2",
            "            if ($parts.Length -eq 2 -and $parts[0] -eq $Key) {",
            "                if (-not $updated) {",
            "                    $lines.Add(\"$Key=$Value\")",
            "                    $updated = $true",
            "                }",
            "                continue",
            "            }",
            string.Empty,
            "            $lines.Add($line)",
            "        }",
            "    }",
            string.Empty,
            "    if (-not $updated) {",
            "        $lines.Add(\"$Key=$Value\")",
            "    }",
            string.Empty,
            "    $lines | Set-Content -Path $Path -Encoding UTF8",
            "}",
            string.Empty,
            "function Ensure-EnvValue([string]$Path, [string]$Key, [string]$Value) {",
            "    if ([string]::IsNullOrWhiteSpace((Read-EnvValue -Path $Path -Key $Key))) {",
            "        Set-OrAppendEnvValue -Path $Path -Key $Key -Value $Value",
            "    }",
            "}",
            string.Empty,
            "function Resolve-PowerShellRuntimePath {",
            "    foreach ($candidate in @('pwsh.exe', 'powershell.exe', 'pwsh', 'powershell')) {",
            "        $command = Get-Command $candidate -ErrorAction SilentlyContinue",
            "        if ($command) {",
            "            return $command.Source",
            "        }",
            "    }",
            string.Empty,
            "    Fail 'PowerShell runtime was not found for NSSM service registration.'",
            "}",
            string.Empty,
            "function Resolve-NssmPath {",
            "    $candidates = @()",
            "    $bundledNssm = Join-Path $InstallDir 'bin/tools/nssm/nssm.exe'",
            "    if (Test-Path $bundledNssm) {",
            "        $candidates += $bundledNssm",
            "    }",
            string.Empty,
            "    if (-not [string]::IsNullOrWhiteSpace($env:CORTEX_WORKER_NSSM_PATH)) {",
            "        $candidates += $env:CORTEX_WORKER_NSSM_PATH",
            "    }",
            string.Empty,
            "    foreach ($candidate in @('nssm.exe', 'nssm')) {",
            "        $command = Get-Command $candidate -ErrorAction SilentlyContinue",
            "        if ($command) {",
            "            $candidates += $command.Source",
            "        }",
            "    }",
            string.Empty,
            "    foreach ($root in @($env:ProgramFiles, ${env:ProgramFiles(x86)}, $env:ChocolateyInstall)) {",
            "        if ([string]::IsNullOrWhiteSpace($root)) {",
            "            continue",
            "        }",
            string.Empty,
            "        foreach ($relativePath in @('nssm/win64/nssm.exe', 'nssm/win32/nssm.exe', 'nssm/nssm.exe', 'bin/nssm.exe')) {",
            "            $candidates += Join-Path $root $relativePath",
            "        }",
            "    }",
            string.Empty,
            "    foreach ($candidate in $candidates | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -Unique) {",
            "        if (Test-Path $candidate) {",
            "            return (Resolve-Path $candidate).Path",
            "        }",
            "    }",
            string.Empty,
            "    Fail 'nssm.exe was not found. The bundled Windows worker package should include tools/nssm/nssm.exe; otherwise set CORTEX_WORKER_NSSM_PATH.'",
            "}",
            string.Empty,
            "function Install-OrUpdateNssmService([string]$NssmPath, [string]$ServiceName, [string]$DisplayName, [string]$LauncherPath, [string]$WorkingDirectory) {",
            "    $existingService = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue",
            "    if ($existingService) {",
            "        if (-not $forceInstall) {",
            "            Fail \"NSSM service '$ServiceName' already exists. Re-run with CORTEX_WORKER_INSTALL_FORCE=true to replace it.\"",
            "        }",
            string.Empty,
            "        if ($existingService.Status -ne 'Stopped') {",
            "            Log \"stopping existing NSSM service $ServiceName\"",
            "            & $NssmPath stop $ServiceName | Out-Null",
            "            Start-Sleep -Seconds 1",
            "        }",
            string.Empty,
            "        Log \"removing existing NSSM service $ServiceName\"",
            "        & $NssmPath remove $ServiceName confirm | Out-Null",
            "        Start-Sleep -Seconds 1",
            "    }",
            string.Empty,
            "    $powerShellRuntime = Resolve-PowerShellRuntimePath",
            "    $launcherArguments = \"-NoLogo -NoProfile -ExecutionPolicy Bypass -File `\"$LauncherPath`\"\"",
            "    $logsDirectory = Join-Path $WorkingDirectory 'logs'",
            "    New-Item -ItemType Directory -Force -Path $logsDirectory | Out-Null",
            string.Empty,
            "    Log \"registering NSSM service $ServiceName\"",
            "    & $NssmPath install $ServiceName $powerShellRuntime $launcherArguments | Out-Null",
            "    & $NssmPath set $ServiceName AppDirectory $WorkingDirectory | Out-Null",
            "    & $NssmPath set $ServiceName DisplayName $DisplayName | Out-Null",
            "    & $NssmPath set $ServiceName Description \"Cortex Terminal worker service for $DisplayName\" | Out-Null",
            "    & $NssmPath set $ServiceName Start SERVICE_AUTO_START | Out-Null",
            "    & $NssmPath set $ServiceName AppExit Default Restart | Out-Null",
            "    & $NssmPath set $ServiceName AppStdout (Join-Path $logsDirectory 'worker-service.stdout.log') | Out-Null",
            "    & $NssmPath set $ServiceName AppStderr (Join-Path $logsDirectory 'worker-service.stderr.log') | Out-Null",
            "    & $NssmPath set $ServiceName AppRotateFiles 1 | Out-Null",
            "    & $NssmPath set $ServiceName AppRotateOnline 1 | Out-Null",
            "}",
            string.Empty,
            "$workerAssetName = 'cortex-terminal-worker-win-x64.zip'",
            "$packageUrl = \"$packageBaseUrl/$workerAssetName\"",
            "$tempDir = Join-Path ([System.IO.Path]::GetTempPath()) (\"ct-worker-\" + [Guid]::NewGuid().ToString('N'))",
            "$archivePath = Join-Path $tempDir $workerAssetName",
            "$packageRoot = Join-Path $tempDir 'package'",
            "New-Item -ItemType Directory -Force -Path $tempDir | Out-Null",
            string.Empty,
            "try {",
            "    Log \"downloading worker package from $packageUrl\"",
            "    Invoke-WebRequest -UseBasicParsing -Uri $packageUrl -OutFile $archivePath",
            string.Empty,
            "    Log 'extracting worker package'",
            "    New-Item -ItemType Directory -Force -Path $packageRoot | Out-Null",
            "    Expand-Archive -Path $archivePath -DestinationPath $packageRoot -Force",
            string.Empty,
            "    $installScript = Join-Path $packageRoot 'scripts/install-worker.ps1'",
            "    if (-not (Test-Path $installScript)) {",
            "        Fail 'install script was not found in downloaded package'",
            "    }",
            string.Empty,
            "    $packageVersion = Read-VersionFile (Join-Path $packageRoot 'package-version.txt')",
            "    $installedVersion = Read-VersionFile (Join-Path $InstallDir 'package-version.txt')",
            "    switch (Compare-PackageVersion $packageVersion $installedVersion) {",
            "        'Same' {",
            "            Log \"worker version $packageVersion is already installed at $InstallDir; skipping upgrade\"",
            "            exit 0",
            "        }",
            "        'Older' {",
            "            Fail \"refusing to downgrade worker from $installedVersion to $packageVersion\"",
            "        }",
            "        'Newer' {",
            "            Log \"upgrading worker from $installedVersion to $packageVersion\"",
            "        }",
            "    }",
            string.Empty,
            "    $bootstrapPayload = @{ token = $installToken } | ConvertTo-Json -Compress",
            "    Log 'requesting worker registration key'",
            "    $workerRegistrationKey = Invoke-RestMethod -Uri \"$gatewayBaseUrl/api/worker/install/registration-key\" -Method Post -ContentType 'application/json' -Body $bootstrapPayload",
            "    if ([string]::IsNullOrWhiteSpace($workerRegistrationKey)) {",
            "        Fail 'gateway returned an empty registration key'",
            "    }",
            string.Empty,
            "    if ($forceInstall) {",
            "        & $installScript -InstallDir $InstallDir -Force",
            "    }",
            "    else {",
            "        & $installScript -InstallDir $InstallDir",
            "    }",
            string.Empty,
            "    $configDir = Join-Path $InstallDir 'config'",
            "    $envFile = Join-Path $configDir 'worker.env'",
            "    $workerHome = Get-WorkerHomePath",
            "    $uninstallPath = Join-Path $InstallDir 'uninstall-worker.ps1'",
            "    New-Item -ItemType Directory -Force -Path $configDir | Out-Null",
            "    $existingWorkerId = Read-EnvValue -Path $envFile -Key 'WORKER_ID'",
            "    $workerName = if ([string]::IsNullOrWhiteSpace($existingWorkerId)) { \"$(Normalize-HostName ([System.Net.Dns]::GetHostName()))-$([Guid]::NewGuid().ToString('N').Substring(0, 6))\" } else { $existingWorkerId }",
            "    $workerDisplayName = $workerName",
            string.Empty,
            "    Set-OrAppendEnvValue -Path $envFile -Key 'GATEWAY_BASE_URL' -Value $gatewayBaseUrl",
            "    Set-OrAppendEnvValue -Path $envFile -Key 'WORKER_ID' -Value $workerName",
            "    Ensure-EnvValue -Path $envFile -Key 'WORKER_USER_KEY' -Value $workerRegistrationKey",
            "    Ensure-EnvValue -Path $envFile -Key 'WORKER_LOG_LEVEL' -Value 'Information'",
            string.Empty,
            "    $launcherPath = Join-Path $InstallDir 'run-worker.ps1'",
            "    $nssmPath = Resolve-NssmPath",
            "    $serviceName = if ([string]::IsNullOrWhiteSpace($env:CORTEX_WORKER_WINDOWS_SERVICE_NAME)) { \"CortexTerminalWorker-$workerName\" } else { $env:CORTEX_WORKER_WINDOWS_SERVICE_NAME.Trim() }",
            "    $serviceDisplayName = if ([string]::IsNullOrWhiteSpace($env:CORTEX_WORKER_WINDOWS_SERVICE_DISPLAY_NAME)) { $workerDisplayName } else { $env:CORTEX_WORKER_WINDOWS_SERVICE_DISPLAY_NAME.Trim() }",
            "    Log \"worker installed to $InstallDir\"",
            "    Install-OrUpdateNssmService -NssmPath $nssmPath -ServiceName $serviceName -DisplayName $serviceDisplayName -LauncherPath $launcherPath -WorkingDirectory $InstallDir",
            "    Log \"starting NSSM service $serviceName\"",
            "    & $nssmPath start $serviceName | Out-Null",
            "    Log \"Windows service installed and started: $serviceName\"",
            "    Log \"uninstall with: pwsh -File $uninstallPath\"",
            "    exit 0",
            "}",
            "finally {",
            "    if (Test-Path $tempDir) {",
            "        Remove-Item -Recurse -Force $tempDir",
            "    }",
            "}"
        ]);
    }

    public static string BuildUnixInstallUrl(string gatewayBaseUrl, string token)
    {
        return $"{gatewayBaseUrl}/install-worker.sh?token={Uri.EscapeDataString(token)}";
    }

    public static string BuildWindowsInstallUrl(string gatewayBaseUrl, string token)
    {
        return $"{gatewayBaseUrl}/install-worker.ps1?token={Uri.EscapeDataString(token)}";
    }

    public static string BuildUnixCommand(string installUrl)
    {
        return $"curl -fsSL '{installUrl}' | bash";
    }

    public static string BuildWindowsCommand(string installUrl)
    {
        return "powershell -NoLogo -NoProfile -ExecutionPolicy Bypass -Command \"& ([ScriptBlock]::Create((Invoke-WebRequest -UseBasicParsing "
            + PowerShellEscape(installUrl)
            + ").Content))\"";
    }

    private static string ShellEscape(string value)
    {
        return $"'{value.Replace("'", "'\"'\"'")}'";
    }

    private static string PowerShellEscape(string value)
    {
        return $"'{value.Replace("'", "''")}'";
    }
}